# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_status',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apply',
            name='bought_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='apply',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='borrow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ncse.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='borrow_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.IntegerField(default=1),
        ),
    ]
